//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xavHub.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourLogo</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerID</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App1"]));
            }
            set {
                this["App1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KeyAuth Panel")]
        public string ProgramName {
            get {
                return ((string)(this["ProgramName"]));
            }
            set {
                this["ProgramName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>panelName</string>
  <string>panelSecret</string>
  <string>panelColor</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Panel1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Panel1"]));
            }
            set {
                this["Panel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>panelName</string>
  <string>panelSecret</string>
  <string>panelColor</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Panel2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Panel2"]));
            }
            set {
                this["Panel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>panelName</string>
  <string>panelSecret</string>
  <string>panelColor</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Panel3 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Panel3"]));
            }
            set {
                this["Panel3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>panelName</string>
  <string>panelSecret</string>
  <string>panelColor</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Panel4 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Panel4"]));
            }
            set {
                this["Panel4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>panelName</string>
  <string>panelSecret</string>
  <string>panelColor</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Panel5 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Panel5"]));
            }
            set {
                this["Panel5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>panelName</string>
  <string>panelSecret</string>
  <string>panelColor</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Panel6 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Panel6"]));
            }
            set {
                this["Panel6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Setting {
            get {
                return ((global::System.Drawing.Color)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Panel1Color {
            get {
                return ((global::System.Drawing.Color)(this["Panel1Color"]));
            }
            set {
                this["Panel1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Panel2Color {
            get {
                return ((global::System.Drawing.Color)(this["Panel2Color"]));
            }
            set {
                this["Panel2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Panel3Color {
            get {
                return ((global::System.Drawing.Color)(this["Panel3Color"]));
            }
            set {
                this["Panel3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Panel4Color {
            get {
                return ((global::System.Drawing.Color)(this["Panel4Color"]));
            }
            set {
                this["Panel4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Panel5Color {
            get {
                return ((global::System.Drawing.Color)(this["Panel5Color"]));
            }
            set {
                this["Panel5Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Panel6Color {
            get {
                return ((global::System.Drawing.Color)(this["Panel6Color"]));
            }
            set {
                this["Panel6Color"] = value;
            }
        }
    }
}
